apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: urdraw-workspace-frontend-v2
  namespace: urdraw
  labels:
    app: urdraw-workspace-frontend-v2
spec:
  serviceName: urdraw-workspace-frontend-v2
  replicas: 2
  selector:
    matchLabels:
      app: urdraw-workspace-frontend-v2
  template:
    metadata:
      labels:
        app: urdraw-workspace-frontend-v2
    spec:
      containers:
        - name: urdraw-workspace-frontend-v2
          image: ideavn/urdraw-workspace-frontend-v2:v{latest}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 64m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: urdraw-workspace-frontend-v2-service
  namespace: urdraw
spec:
  selector:
    app: urdraw-workspace-frontend-v2
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urdraw-workspace-frontend-v2-ingress
  namespace: urdraw
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: v2.urdraw.click
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: urdraw-workspace-frontend-v2-service
            port:
              number: 3000
