apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: urdraw-content-backend
  namespace: urdraw
  labels:
    app: urdraw-content-backend
spec:
  serviceName: urdraw-content-backend
  replicas: 2
  selector:
    matchLabels:
      app: urdraw-content-backend
  template:
    metadata:
      labels:
        app: urdraw-content-backend
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'urdraw-content-backend-dev'
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-env-config: 'kv/urdraw-content-backend-dev'
        vault.hashicorp.com/agent-inject-template-env-config: |
            {{ with secret "kv/urdraw-content-backend-dev" -}}
              {{- range $key, $value := .Data.data }}
                export {{ $key }}="{{ $value }}"
              {{- end }}
            {{- end }}
    spec:
      serviceAccountName: urdraw-content-backend-dev-auth
      containers:
        - name: urdraw-content-backend
          image: ideavn/urdraw-content-backend:v{latest}
          ports:
            - containerPort: 3009
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 64m
              memory: 64m
---
apiVersion: v1
kind: Service
metadata:
  name: urdraw-content-backend-service
  namespace: urdraw
spec:
  selector:
    app: urdraw-content-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3009
      targetPort: 3009
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urdraw-content-backend-ingress
  namespace: urdraw
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  rules:
  - host: api-p.urdraw.click
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: urdraw-content-backend-service
            port:
              number: 3009
